# Generated by Django 6.1 on 2026-08-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGastoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gasto',
                'db_table': 'categorias_gasto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelPrioridadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('nivel_orden', models.SmallIntegerField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Nivel de prioridad',
                'verbose_name_plural': 'Niveles de prioridad',
                'db_table': 'niveles_prioridad',
                'managed': False,
            },
        ),
    ]
