/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alertas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar alertas por estado
         * @description Alertas del usuario autenticado en un estado dado (Pendiente/Enviada/Leida/Resuelta).
         */
        get: operations["alertas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alertas/{alerta_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar estado de una alerta
         * @description Aplica una transición manual de estado: Pendiente -> Enviada, o Enviada -> Leida. 'Resuelta' no se setea por acá: ocurre sola cuando se registra el pago del servicio fijo correspondiente.
         */
        patch: operations["alertas_partial_update"];
        trace?: never;
    };
    "/api/alertas/generar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generar alertas de vencimiento
         * @description Crea alertas 'Pendiente' para los servicios fijos próximos a vencer (parado en `fecha`, por defecto hoy). Idempotente: no duplica alertas ya generadas para el mismo servicio/periodo.
         */
        post: operations["alertas_generar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogos/categorias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar categorías de gasto
         * @description Categorías globales del sistema (usuario_id nulo) + las personalizadas del usuario autenticado.
         */
        get: operations["catalogos_categorias_list"];
        put?: never;
        /**
         * Crear categoría personalizada
         * @description Crea una categoría de gasto propia del usuario autenticado.
         */
        post: operations["catalogos_categorias_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalogos/niveles-prioridad/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar niveles de prioridad
         * @description Catálogo fijo de solo lectura (Esencial, Importante, Prescindible), ordenado por nivel_orden.
         */
        get: operations["catalogos_niveles_prioridad_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gastos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar gastos del periodo
         * @description Gastos del usuario autenticado en el periodo (mes, año) indicado (puntuales y pagos de servicio fijo).
         */
        get: operations["gastos_list"];
        put?: never;
        /**
         * Registrar un gasto puntual
         * @description Da de alta un gasto NO ligado a un servicio fijo (mercado, salidas, compras varias).
         */
        post: operations["gastos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gastos/balance-mensual/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Balance mensual
         * @description total_ingresos - total_gastos del usuario autenticado en el periodo indicado.
         */
        get: operations["gastos_balance_mensual_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gastos/modo-emergencia/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Simular modo emergencia
         * @description Gasto por prioridad del periodo y ahorro acumulado si se suspenden los gastos más prescindibles.
         */
        get: operations["gastos_modo_emergencia_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gastos/pagos-servicio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar pago de un servicio fijo
         * @description Registra el pago de un servicio fijo para un periodo (categoría/prioridad se deducen del propio servicio).
         */
        post: operations["gastos_pagos_servicio_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gastos/variacion-servicios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Variación mes a mes de un servicio fijo
         * @description Por cada periodo pagado de un servicio fijo, el % de variación respecto al pago anterior.
         */
        get: operations["gastos_variacion_servicios_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingresos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ingresos del periodo
         * @description Ingresos del usuario autenticado en el periodo (mes, año) indicado, ordenados por fecha.
         */
        get: operations["ingresos_list"];
        put?: never;
        /**
         * Registrar un ingreso
         * @description Da de alta un ingreso del usuario autenticado en un periodo.
         */
        post: operations["ingresos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingresos/total-periodo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Total de ingresos del periodo
         * @description Suma de los ingresos del usuario autenticado en el periodo (mes, año) indicado.
         */
        get: operations["ingresos_total_periodo_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planes-financieros/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar planes financieros
         * @description Todos los planes (activos e inactivos) del usuario autenticado, más nuevo primero.
         */
        get: operations["planes_financieros_list"];
        put?: never;
        /**
         * Crear plan financiero
         * @description Crea un plan (nace inactivo). Los 3 porcentajes deben sumar 100.
         */
        post: operations["planes_financieros_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planes-financieros/{plan_id}/activar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activar un plan financiero
         * @description Marca `plan_id` como el plan activo del usuario, desactivando el anterior si existía.
         */
        post: operations["planes_financieros_activar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/planes-financieros/comparativa/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comparar plan activo vs. ejecución real
         * @description Metas del plan activo (gasto fijo/ahorro/gasto libre) vs. ingresos y gastos reales del periodo.
         */
        get: operations["planes_financieros_comparativa_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicios-fijos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar servicios fijos activos
         * @description Servicios fijos activos (activo=True) del usuario autenticado, ordenados por nombre.
         */
        get: operations["servicios_fijos_list"];
        put?: never;
        /**
         * Crear servicio fijo
         * @description Da de alta un servicio fijo / gasto recurrente (ej. Internet, Agua, Gimnasio).
         */
        post: operations["servicios_fijos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/servicios-fijos/proximos-a-vencer/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Servicios próximos a vencer
         * @description Servicios fijos activos cuyo vencimiento cae dentro de su ventana de anticipación, parado en `fecha` (por defecto, hoy). Insumo del generador de alertas.
         */
        get: operations["servicios_fijos_proximos_a_vencer_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Valida email + contraseña. Si son correctos y el usuario está activo, devuelve el usuario + un par de tokens JWT: guardá `access` y mandalo como 'Authorization: Bearer <access>' en el resto de la API.
         */
        post: operations["usuarios_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/registro/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un usuario nuevo
         * @description Alta de usuario (crea el perfil en `usuarios` y su auth.User vinculado). El email debe ser único; la contraseña se guarda hasheada. Devuelve el usuario ya autenticado (access + refresh), no hace falta llamar a /login/ después.
         */
        post: operations["usuarios_registro_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["usuarios_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AhorroEmergencia: {
            prioridad: string;
            nivel_orden: number;
            /** Format: decimal */
            total_periodo: string;
            /** Format: decimal */
            ahorro_acumulado_si_suspende: string;
        };
        AlertaPago: {
            readonly id: number;
            readonly usuario_id: number;
            servicio_fijo_id: number;
            readonly gasto_id: number | null;
            periodo_mes: number;
            periodo_anio: number;
            /** Format: date */
            fecha_alerta: string;
            readonly estado: components["schemas"]["AlertaPagoEstadoEnum"];
            mensaje?: string | null;
        };
        /**
         * @description * `Pendiente` - Pendiente
         *     * `Enviada` - Enviada
         *     * `Leida` - Leida
         *     * `Resuelta` - Resuelta
         * @enum {string}
         */
        AlertaPagoEstadoEnum: "Pendiente" | "Enviada" | "Leida" | "Resuelta";
        BalanceMensual: {
            usuario_id: number;
            periodo_mes: number;
            periodo_anio: number;
            /** Format: decimal */
            total_ingresos: string;
            /** Format: decimal */
            total_gastos: string;
            /** Format: decimal */
            balance: string;
        };
        /**
         * @description * `Enviada` - Enviada
         *     * `Leida` - Leida
         * @enum {string}
         */
        CambiarEstadoAlertaEstadoEnum: "Enviada" | "Leida";
        CategoriaGasto: {
            readonly id: number;
            readonly usuario_id: number | null;
            nombre: string;
            icono?: string | null;
        };
        ComparativaPlanVsReal: {
            usuario_id: number;
            periodo_mes: number;
            periodo_anio: number;
            /** Format: decimal */
            total_ingresos: string;
            /** Format: decimal */
            meta_gasto_fijo: string;
            /** Format: decimal */
            meta_ahorro: string;
            /** Format: decimal */
            meta_gasto_libre: string;
            /** Format: decimal */
            gasto_real: string;
            /** Format: decimal */
            balance_real: string;
        };
        /** @description Salida generica de un Gasto y entrada de un gasto puntual. */
        Gasto: {
            readonly id: number;
            readonly usuario_id: number;
            categoria_id: number;
            readonly servicio_fijo_id: number | null;
            prioridad_id: number;
            /** Format: decimal */
            monto: string;
            /** Format: date */
            fecha_gasto: string;
            periodo_mes: number;
            periodo_anio: number;
            /** @default Pagado */
            estado: components["schemas"]["GastoEstadoEnum"];
            descripcion?: string | null;
        };
        /**
         * @description * `Pagado` - Pagado
         *     * `Pendiente` - Pendiente
         *     * `Vencido` - Vencido
         * @enum {string}
         */
        GastoEstadoEnum: "Pagado" | "Pendiente" | "Vencido";
        Ingreso: {
            readonly id: number;
            readonly usuario_id: number;
            /** Format: decimal */
            monto: string;
            /** Format: date */
            fecha: string;
            periodo_mes: number;
            periodo_anio: number;
            fuente?: string | null;
            descripcion?: string | null;
        };
        /** @description Entrada de POST /api/usuarios/login/. */
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        NivelPrioridad: {
            readonly id: number;
            nombre: string;
            nivel_orden: number;
            descripcion?: string | null;
            color?: string | null;
        };
        /** @description Entrada de PATCH /api/alertas/<id>/ : a que estado pasar. */
        PatchedCambiarEstadoAlerta: {
            estado?: components["schemas"]["CambiarEstadoAlertaEstadoEnum"];
        };
        PlanFinanciero: {
            readonly id: number;
            readonly usuario_id: number;
            /** @default Mi plan */
            nombre: string;
            /** Format: decimal */
            porcentaje_gasto_fijo: string;
            /** Format: decimal */
            porcentaje_ahorro: string;
            /** Format: decimal */
            porcentaje_gasto_libre: string;
            /** Format: date */
            fecha_inicio?: string;
            /** Format: date */
            fecha_fin?: string | null;
            readonly activo: boolean;
        };
        /**
         * @description Entrada de POST /api/gastos/pagos-servicio/. categoria_id y
         *     prioridad_id NO van acá: la vista los deduce del propio servicio
         *     fijo (servicio.categoria_id / servicio.prioridad_id).
         */
        RegistrarPagoServicioFijo: {
            servicio_fijo_id: number;
            /** Format: decimal */
            monto: string;
            /** Format: date */
            fecha_gasto: string;
            periodo_mes: number;
            periodo_anio: number;
            descripcion?: string | null;
        };
        /** @description Entrada de POST /api/usuarios/registro/. */
        RegistroUsuario: {
            nombre: string;
            /** Format: email */
            email: string;
            password: string;
        };
        ServicioFijo: {
            readonly id: number;
            readonly usuario_id: number;
            categoria_id: number;
            prioridad_id: number;
            nombre: string;
            dia_vencimiento: number;
            /** Format: decimal */
            monto_estimado?: string | null;
            /** @default false */
            es_monto_variable: boolean;
            /** @default 3 */
            dias_anticipacion_alerta: number;
            readonly activo: boolean;
            /** Format: date */
            fecha_inicio?: string;
            /** Format: date */
            fecha_fin?: string | null;
            notas?: string | null;
        };
        /**
         * @description Salida de registro/login: el usuario + el par de tokens JWT.
         *     El front guarda `access` y lo manda como
         *     'Authorization: Bearer <access>' en cada request. Cuando expira
         *     (ACCESS_TOKEN_LIFETIME, ver settings), usa `refresh` contra
         *     POST /api/usuarios/token/refresh/ para obtener un access nuevo sin
         *     volver a pedir la contrasena.
         */
        TokenAuth: {
            usuario: components["schemas"]["Usuario"];
            access: string;
            refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /** @description Salida de GET /api/ingresos/total-periodo/. */
        TotalIngresosPeriodo: {
            periodo_mes: number;
            periodo_anio: number;
            /** Format: decimal */
            total_ingresos: string;
        };
        /** @description Salida: lo que la API devuelve de un Usuario. */
        Usuario: {
            readonly id: number;
            nombre: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            readonly fecha_registro: string;
            readonly activo: boolean;
        };
        VariacionServicio: {
            servicio_fijo_id: number;
            servicio: string;
            periodo_mes: number;
            periodo_anio: number;
            /** Format: decimal */
            monto_actual: string;
            /** Format: decimal */
            monto_anterior: string | null;
            /** Format: decimal */
            porcentaje_variacion: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alertas_list: {
        parameters: {
            query?: {
                /** @description Pendiente (default) | Enviada | Leida | Resuelta. */
                estado?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaPago"][];
                };
            };
        };
    };
    alertas_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alerta_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCambiarEstadoAlerta"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCambiarEstadoAlerta"];
                "multipart/form-data": components["schemas"]["PatchedCambiarEstadoAlerta"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaPago"];
                };
            };
            /** @description No existe la alerta. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Transición de estado no permitida. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    alertas_generar_create: {
        parameters: {
            query?: {
                /** @description Fecha de referencia (YYYY-MM-DD). También se acepta en el body. Por defecto, hoy. */
                fecha?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertaPago"][];
                };
            };
        };
    };
    catalogos_categorias_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaGasto"][];
                };
            };
        };
    };
    catalogos_categorias_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaGasto"];
                "application/x-www-form-urlencoded": components["schemas"]["CategoriaGasto"];
                "multipart/form-data": components["schemas"]["CategoriaGasto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaGasto"];
                };
            };
            /** @description Ya existe una categoría con ese nombre para este usuario. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    catalogos_niveles_prioridad_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NivelPrioridad"][];
                };
            };
        };
    };
    gastos_list: {
        parameters: {
            query: {
                /** @description Año del periodo. */
                anio: number;
                /** @description Mes del periodo (1-12). */
                mes: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gasto"][];
                };
            };
        };
    };
    gastos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Gasto"];
                "application/x-www-form-urlencoded": components["schemas"]["Gasto"];
                "multipart/form-data": components["schemas"]["Gasto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gasto"];
                };
            };
            /** @description Monto o estado inválido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gastos_balance_mensual_retrieve: {
        parameters: {
            query: {
                /** @description Año del periodo. */
                anio: number;
                /** @description Mes del periodo (1-12). */
                mes: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceMensual"];
                };
            };
        };
    };
    gastos_modo_emergencia_list: {
        parameters: {
            query: {
                /** @description Año del periodo. */
                anio: number;
                /** @description Mes del periodo (1-12). */
                mes: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AhorroEmergencia"][];
                };
            };
        };
    };
    gastos_pagos_servicio_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarPagoServicioFijo"];
                "application/x-www-form-urlencoded": components["schemas"]["RegistrarPagoServicioFijo"];
                "multipart/form-data": components["schemas"]["RegistrarPagoServicioFijo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gasto"];
                };
            };
            /** @description Monto inválido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description servicio_fijo_id inexistente. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ya existe un pago de ese servicio en ese periodo. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gastos_variacion_servicios_list: {
        parameters: {
            query: {
                servicio_fijo_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariacionServicio"][];
                };
            };
        };
    };
    ingresos_list: {
        parameters: {
            query: {
                /** @description Año del periodo. */
                anio: number;
                /** @description Mes del periodo (1-12). */
                mes: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingreso"][];
                };
            };
        };
    };
    ingresos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ingreso"];
                "application/x-www-form-urlencoded": components["schemas"]["Ingreso"];
                "multipart/form-data": components["schemas"]["Ingreso"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingreso"];
                };
            };
            /** @description Monto o periodo inválido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ingresos_total_periodo_retrieve: {
        parameters: {
            query: {
                /** @description Año del periodo. */
                anio: number;
                /** @description Mes del periodo (1-12). */
                mes: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotalIngresosPeriodo"];
                };
            };
        };
    };
    planes_financieros_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanFinanciero"][];
                };
            };
        };
    };
    planes_financieros_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanFinanciero"];
                "application/x-www-form-urlencoded": components["schemas"]["PlanFinanciero"];
                "multipart/form-data": components["schemas"]["PlanFinanciero"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanFinanciero"];
                };
            };
            /** @description Los porcentajes no suman 100. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    planes_financieros_activar_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanFinanciero"];
                };
            };
            /** @description No existe el plan. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    planes_financieros_comparativa_retrieve: {
        parameters: {
            query: {
                /** @description Año del periodo. */
                anio: number;
                /** @description Mes del periodo (1-12). */
                mes: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparativaPlanVsReal"];
                };
            };
            /** @description El usuario no tiene un plan activo. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    servicios_fijos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioFijo"][];
                };
            };
        };
    };
    servicios_fijos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServicioFijo"];
                "application/x-www-form-urlencoded": components["schemas"]["ServicioFijo"];
                "multipart/form-data": components["schemas"]["ServicioFijo"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioFijo"];
                };
            };
            /** @description dia_vencimiento, monto_estimado o rango de fechas inválido. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    servicios_fijos_proximos_a_vencer_list: {
        parameters: {
            query?: {
                /** @description Fecha de referencia (YYYY-MM-DD). Por defecto, hoy. */
                fecha?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServicioFijo"][];
                };
            };
        };
    };
    usuarios_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenAuth"];
                };
            };
            /** @description Email o contraseña incorrectos, o usuario inactivo. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    usuarios_registro_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistroUsuario"];
                "application/x-www-form-urlencoded": components["schemas"]["RegistroUsuario"];
                "multipart/form-data": components["schemas"]["RegistroUsuario"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenAuth"];
                };
            };
            /** @description Ya existe un usuario con ese email. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    usuarios_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
}
